name: Compose Action
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose an environment [QA / TEST]"
        required: true
        type: choice
        options: [qa, test]
  push:
    branches: [main, feature]
    paths-ignore: ['.github/**']
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Use custom action
        uses: ./.github/actions
        id: cache-deps
        with:
          caching: false
      - name: Tell if cache was done
        run: |
          echo "Was it cached ? ${{steps.cache-deps.outputs.caching-flag}}"

  build:
    needs: lint
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Use custom once again
        uses: ./.github/actions
  report:
    needs: build
    if: always() #cancelled()
    uses: "./.github/workflows/reusable.yml"
    with:
      myInput: "lalal la la la two 6"   #
    secrets:
      some-secret: ${{secrets.PASSWORD_ENV}}
  print-report:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Print results from previous job output
        run: echo "${{ needs.report.outputs.resultX}}"
