name: Compose Action
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose an environment [QA / TEST]"
        required: true
        type: choice
        options: [qa, test]
  push:
    branches: [main, feature]
    paths-ignore: ['.github/**']
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Use custom action
        id: cache-deps
        uses: ./.github/actions/compose
        with:
          caching: 'true'
      - name: Tell if cache was done
        run: |
          echo "Was it cached ? ${{ steps.cache-deps.outputs.caching-flag }}"

  build:
    needs: lint
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Use custom once again
        id: customAction
        uses: ./.github/actions/compose
      - name: Tell if cache was done
        run: |
          echo "Was it cached ? ${{ steps.customAction.outputs.caching-flag }}"

  report:
    needs: build
    if: always() #cancelled()
    uses: "./.github/workflows/reusable.yml"
    with:
      myInput: "lalal la la la two 6"   #
    secrets:
      some-secret: ${{secrets.PASSWORD_ENV}}
  print-report:
    needs: report
    runs-on: ubuntu-latest
    steps:
      - name: Print results from previous job output
        run: echo "${{ needs.report.outputs.resultX}}"
  deploy-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Run custom action
        uses: './.github/js'
        id: deployAws
        env:
          AWS_ACCESS_KEY_ID: 144312SDSATEST
          AWS_SECRET_ACCESS_KEY: 3222TEST
        with:
          bucket: gha-custom-action-hosting
          dist-folder: ./.github/workflows
      - name: Output info
        if: always()
        run: |
          echo "Live URL: ${{ steps.deployAws.outputs.website-url}} "
          
