name: Deployment Exercise 4 - flow control
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Choose an environment [QA / TEST]"
        required: true
        type: choice
        options: [qa, test]
  push:
    branches: [main, feature]
    paths-ignore: ['.github/**']
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Test the code on ${{ github.event.inputs.env }}
        id: idRunTest
        run: |
          echo "test variable: ${{ vars.MYVARIABLE_ENV }} "

      - name: Run this if prev failed
        if: failure() && steps.idRunTest.outcome == 'failure'           # failure() true if any step fail,# success() true if all steps ok # always(), cancelled()
                                                                        # step will be done if there was an error but TEST will FAIL
        run: |
          echo "This step should run only if previous step failed"
      - name: Run this even if there was an error
        continue-on-error: true                                         # always continue - even if there is an error
                                                                        # !! the Test will pass even if there is an error TEST will PASS
        run: |
          echo "always continue - even if there is an error"
  build:
    needs: lint
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.env}}-build
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Build
        run: |
          echo "Build the code"
  report:
    needs: build
    if: always() #cancelled()
    uses: "./.github/workflows/reusable.yml"
    with:
      myInput: "lalal la la la"   #
    secrets:
      some-secret: ${{secrets.PASSWORD_ENV}}
