name: First Workflow                # name of workflow
on: workflow_dispatch               # to run manually

permissions:
  contents: read
  checks: write
  issues: read
  packages: read
  pull-requests: write

jobs:
  my-first-job:                        #name for job
    name: Run cos on Ubuntu
    runs-on: ubuntu-latest              #runners
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Print greeting
        run: echo "Hello World"
      
      - name: Print goodbye
        run: echo "Done - bye bye!"

      - name: Run gatling
        run: |
          gradle gatlingRun-acetoys.RecordedSimulation
        
    
