name: First Workflow                # name of workflow
on: workflow_dispatch               # to run manually

jobs:
  my-first-job:                        #name for job
    name: Run cos on Ubuntu
    runs-on: ubuntu-latest              #runners
    steps:
      - name: Print greeting
        run: echo "Hello World"
      
      - name: Print goodbye
        run: echo "Done - bye bye!"

      - name: Run gatling
        run: |
          ./gradlew gatlingRun-acetoys.RecordedSimulation
        
    
