name: Performance test                # name of workflow
on: workflow_dispatch               # to run manually

permissions:
  contents: read
  checks: write
  issues: read
  packages: read
  pull-requests: write

jobs:
  my-first-job:                        #name for job
    name: Run cos on Ubuntu
    runs-on: ubuntu-latest              #runners
    outputs:
      firstJob-output: ${{ steps.stepId.myOutput }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print greeting
        run: echo "Hello World"
      
      - name: Print goodbye
        run: echo "Done - bye bye!"

      - name: Publish output                            # output - is special variable,we can pass to another job
        id: stepId
        run: echo 'myOutput= testowa zmienna' >> $GITHUB_OUTPUT ';'

      - name: Run gatling
        run: |
          ./gradlew gatlingRun-acetoys.RecordedSimulation

      - name: Publish smoke test artifacts            # artifact - this step produce special data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/reports/gatling
          retention-days: 7
  my-second-job:
    needs: my-first-job
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
      - name: Output contents
        run: ls
      - name: Get output from prev job
        run: echo $ {{ needs.my-first-job.outputs.firstJob-output}}

    
