name: Reusable Publish
on:
  workflow_call:
    inputs:
      myInput:
        description: Inputs from other workflow
        required: true
        default: myInId
        type: string
    secrets:
      some-secret:
        required: true


jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable output information
        run: echo "Publish & send it ... ${{ inputs.myInput}}, and the secret is ${{secrets.some-secret}}"