name: ACE Toys Performance Test
on:
  workflow_dispatch:
  push:
    branches: [ feature ]

  #this is second workflow 2

jobs:
  pre-job:
    name: Prepare environment
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: |
          echo "Hello world!"
          echo "Goodbye everyone ;( "

  perf-test:
    name: Performance tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rung gatling script
        run: |
          ./gradlew gatlingRun-acetoys.RecordedSimulation \


