name: ACE Toys Performance Test
on:
  workflow_dispatch:
  push:
    branches: [ feature ]

  #this is second workflow 234

jobs:
  pre-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: |
          echo "Goodbye everyone ;(  ${{ toJSON(github) }}"
  second-job:                      #jobs run parallel - untill you add needs
    runs-on: ubuntu-latest
    steps:
      - name: Say something
        run: |
          echo "Hello world!"

  perf-test:
    needs: [pre-job]        #now job run one after another
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Rung gatling script
        run: |
          ./gradlew gatlingRun-acetoys.RecordedSimulation \


